defaults:
  actions:
    squash:
      commit_message: first-commit
pull_request_rules:
  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}
  - name: warn on conflicts
    conditions:
      - conflict
      - '-closed'
    actions:
      comment:
        message: '@{{author}} this pull request is now in conflict 😩'
      label:
        toggle:
          - conflict
  - name: label on unresolved
    conditions:
      - '#review-threads-unresolved>0'
    actions:
      label:
        toggle:
          - review threads unresolved
  - name: warn on CI failure for hotfix
    conditions:
      - '-closed'
      - label=hotfix
      - '#check-failure>0'
    actions:
      comment:
        message: Your hotfix is failing CI @{{author}} 🥺

  - name: label on queued
    conditions:
      - queue-position>=0
    actions:
      label:
        toggle:
          - queued

  - name: Clifus labels
    conditions:
      - base=main
      - author=mergify-ci-bot
      - head~=^clifus/
      - 'title~=^chore: bump'
    actions:
      label:
        add:
          - dependencies
  - name: Trivy label
    conditions:
      - base=main
      - author=mergify-ci-bot
      - head=trivy/daily-report
      - 'body~=New CVEs:'
    actions:
      label:
        add:
          - new CVE
merge_protections:
  - name: Changelog requirements
    if: []
    success_conditions:
      - repository-name != mergify-shadow-office
      - or:
          - '-title ~= ^feat'
          - label = skip changelog
          - label = need changelog
  - name: Enforce conventional commit
    description: Make sure that we follow https://www.conventionalcommits.org/en/v1.0.0/
    if:
      - base = main
    success_conditions:
      - >-
        title ~=
        ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:(.+))?:
