defaults:
  actions:
    queue:
      allow_merging_configuration_change: true
    squash:
      commit_message: first-commit

pull_request_rules:
  - name: dismiss reviews
    conditions: []
    actions:
      dismiss_reviews: {}

  - name: warn on conflicts
    conditions:
      - conflict
      - -closed
    actions:
      comment:
        message: "@{{author}} this pull request is now in conflict 😩"
      label:
        toggle:
          - conflict

  - name: label on unresolved
    conditions:
      - "#review-threads-unresolved>0"
    actions:
      label:
        toggle:
          - review threads unresolved

  - name: warn on CI failure for hotfix
    conditions:
      - -closed
      - label=hotfix
      - "#check-failure>0"
    actions:
      comment:
        message: Your hotfix is failing CI @{{author}} 🥺

  - name: changelog requirements
    conditions:
      - or:
          - "-title~=^feat"
          - label=skip changelog
          - label=need changelog
    actions:
      post_check:
        title: |
          {% if check_succeed %}
          Changelog requirements are present.
          {% else %}
          Changelog requirements are missing.
          {% endif %}


  - name: label on queued
    conditions:
      - queue-position>=0
    actions:
      label:
        toggle:
          - 'queued'

  - name: Conventional Commit
    conditions:
      - base=main
    actions:
      post_check:
        success_conditions:
          - "title ~= ^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\\))?:"
        title: |
          {% if check_succeed %}
          Title follows Conventional Commit
          {% else %}
          Title does not follow Conventional Commit
          {% endif %}
        summary: |
          {% if not check_succeed %}
          The pull request title must follow
          [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/).
          {% endif %}

  - name: Clifus labels
    conditions:
      - base=main
      - author=mergify-ci-bot
      - head~=^clifus/
      - "title~=^chore: bump"
    actions:
      label:
        add:
          - dependencies

  - name: Trivy label
    conditions:
      - base=main
      - author=mergify-ci-bot
      - head=trivy/daily-report
      - "body~=New CVEs:"
    actions:
      label:
        add:
          - new CVE
